#nodeport.yaml
apiVersion: v1
kind: Service
metadata:
    name: nodeport-service
    labels:
        app: nginx
spec:
    type: NodePort
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 80
        nodePort: 30622
    selector:
        app: nginx
