apiVersion: batch/v1
kind: CronJob
metadata: 
 name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
     template:
       spec:
         restartPolicy: OnFailure
         containers:
           - name: hello
             image: busybox:1.28
             imagePolicy: IfNotPresent
             command: ["/bin/sh", "-c", "date; echo hello fromt eh kubernetes cluster"]
