apiVersion: apps/v1
kind: Deployment
metadata: 
    name: hpa-test
spec:
    selector:
        matchLabels:
            app: hpa-test
    replicas: 1
    template:
        metadata:
            labels:
                app: hpa-test
        spec:
            containers:
              - name: hpa-test
                image: nginx
                ports: 
                - containerPort: 80
                resources:
                    limits:
                        cpu: 500m
                    requests:
                        cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
   name: hpa-test
   labels:
      app: hpa-test
spec:
   ports:
     - port: 80
  selector:
      app: hpa-test
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-test
  minReplicas: 1
  macReplicas: 10
  targetCPUUtilizationPercentage: 50

