apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: rb-test
    namespace: student33
subjects:
  - kind: User
    name: student33
roleRef:
    kind: Role
    name: test-role
    apiGroup: rbac.authorization.k8s.io
