apiVersion: apps/v1
kind: Deployment
metadata:
   name: db-env
spec: 
   selector:
      matchLabels: 
         app: mysql
   template: 
      metadata: 
         name: mysql
         labels:
            app: mysql
      spec: 
         containers: 
           - name: mysql
             image: mariadb
             ports:
               - containerPort: 80
             envFrom:
               - secretRef: #configRef:
                 name: db-secret #secret configmap name
             #env:
             # - name: MYSQL_ROOT_PASSWORD
             #   valueFrom:
             #    secretKeyRef: #configMapKeyRef:
             #     name: db-secret # secret configmap name
             #     key: MYSQL_ROOT_PASSWORD
             
             #volumeMounts:
             # - mountPath: /tmp/secret
             #   name: db-secret
             #
         #volumes:
         # - name: db-secret
         #   secret: #configMap
         #    secretName: db-secret

