apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: container1
      image: kubetm/init
      volumeMounts: 
      - name: test-dir
        mountPath: /test1 #container 내부에 test1 마운트
    - name: container2
      image: kubetm/init
      volumeMounts:
      - name: test-dir
        mountPath: /test2 #container 내부에 test2 에 마운트
  volumes:
    - name: test-dir #위 컨테이너 volumeMount name과 일치시키기
      emptyDir: {}
