apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec: 
 nodeSelector:
   kubernetes.io/hostname: grad3-worker-1 #어느 노드에 생성할지를 지정해주는 spec
  containers:
    - name: container
      image: kubetm/init
      volumeMounts:
        - name: test-vol #여기 이름과
          mountPath: /test1 #컨테이너 내부의 mounPath
  volumes:
    - name: test-vol #여기 이름을 맞춰야함
      hostPath: 
       path: /test-volume #워커노드에 만들어지는 dir이름
       type: DirectoryOrCreate #디렉토리가 없을 시 생성함
