spec: 
  containers: 
    - name: container1
      image: kubetm/init
      volumeMounts: 
         - name: test-vol
           mountPath: /test
  volumes: 
    - name: test-vol
      emptyDir: {}
      hostPath: 
        path: /test-vol
        type: DirectoryOrCreate
---
spec: 
   capacity: 
      storage: 1Gi
   accessModes: 
     - 
   persistentVolumeClaimPolict: Retain
   storageClassName: 
   local: 
      path: /home/studetn33/test
   nodeAffinity: 
      required: 
         nodeSelectorTerms: 
            - matchExpressions: 
                - key: kuber..
                  operator: IN
                  values: 
                    - grad3-...
---
spec:
   accessModes: 
     - 
   storageCalssName: 
   volumeName: pv name
   resources: 
      requests: 
         storage: 1Gi
---
#secret make cli command
kubectl create secret generic test-secret --from-literal=Hello=world --from-file=test.tx

---
spec:
   containers: 
     - name: container
       image: mariadb
       ports: 
          - containerPort: 80
       envFrom: 
          - secretRef: configRef:
            name: db-secret
       env: 
          - name: MYSQL_
            valueFrom: 
               secretKeyRef: 
                  name: db-secret #secret name
                  key: 
       volumeMounts: 
          - name: db-secret
            moutPath: 
  volumes: 
     - name: db-secret: 
       secret: 
          secretName: db-secret
       configMap:
          name: db-config
